# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode12.5
language: swift # or objective-c

env:
  - XCODE_WORKSPACE=Example/*.xcworkspace
    XCODE_SCHEME=travis_ci_demo_ios-Example
    XCODE_DESTINATION="platform=iOS Simulator,OS=14.5,name=iPhone 8"

cache: cocoapods
podfile: Example/Podfile
before_install:
  - gem install cocoapods # Since Travis is not always on latest version
  - pod install --project-directory=Example
script:
  - set -o pipefail && xcodebuild -workspace $XCODE_WORKSPACE -scheme $XCODE_SCHEME -destination "$XCODE_DESTINATION" build test | xcpretty
